generateRandom function
byjackli/vibe pull request #18
Opened 2023-07-05 20:20 UTC by aaronli03

## What
- modified generateRandomString to generateRandom
- generateRandom() can be used to construct a state or code verifier
- Changed "Format with Prettier" title to "Check with Prettier"

## Why
- this single function compacts two fuctions into one
- new arg will determine which character set to use
- changed name to correctly represent the intention of command

## Impact
- Will customer experience be significantly altered? No
- Does the code change cover more than one task? No

## Testing
- tested locally by running `npm run dev`

2023-07-05 20:21 UTC, aaronli03 commented
Next pr will address the prettier format warn.

2023-07-08 08:10 UTC, byjackli commented on src/api/auth.ts
> +export const codeVerifierSet = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-._~';
do uppercase `STRING_SET` and `CODE_VERIFIER_SET`

2023-07-08 08:12 UTC, byjackli requested changes
squash all your 3 commits into 1. each PR should only have ONE commit

2023-07-08 08:12 UTC, byjackli commented on src/api/auth.ts
> +export const codeVerifierSet = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-._~';
make sure to update your tests to check against both different sets

2023-07-09 15:53 UTC, byjackli approved these changes
In the future, instead of using `* as` can you try just importing the specifics you need?

2023-07-09 15:57 UTC, merged